import "~/styles/globals.css";

import { GeistSans } from "geist/font/sans";
import { type Metadata } from "next";

import { TRPCReactProvider } from "~/trpc/react";
import ThemeProvider from "~/components/theme-provider";
import { Provider as JotaiProvider } from "jotai";
import NavBar from "./_components/nav-bar";
import { cn } from "~/lib/utils";

export const metadata: Metadata = {
  title: "FoolProof Apps",
  description: "Generated by create-t3-app",
  icons: [{ rel: "icon", url: "/logo.png" }],
};

export default function RootLayout({
  children,
}: Readonly<{ children: React.ReactNode }>) {
  return (
    <html lang="en" className={`${GeistSans.variable}`}>
      <body>
        <TRPCReactProvider>
          <JotaiProvider>
            <ThemeProvider
              attribute="class"
              defaultTheme="system"
              enableSystem
              disableTransitionOnChange
            >
              <main className="relative flex min-h-screen flex-col">
                <div className="relative flex flex-row">
                  <NavBar />
                  <div className="relative flex h-screen w-full flex-1 flex-col">
                    {/* Header */}
                    <div className="flex h-20 bg-red-300"></div>
                    <div className={cn("flex flex-col flex-1 overflow-y-auto p-2")}>
                      {children}
                    </div>
                  </div>
                </div>
              </main>
            </ThemeProvider>
          </JotaiProvider>
        </TRPCReactProvider>
      </body>
    </html>
  );
}
